
package customer.frames;

import employee.UserEmployeeFrame;
import static customer.frames.SearchCustomerFrame.cus;
import customers.entity.Customer;
import java.util.List;
import javax.swing.JOptionPane;
import customer.helperClass.HibernateUtil;
import org.hibernate.HibernateException;
import org.hibernate.Query;
import org.hibernate.Session;
import org.hibernate.Transaction;


public class EditCustomerProfileFrame extends javax.swing.JFrame {

    /**
     * Creates new form EditCustomerProfileFrame
     */
    public EditCustomerProfileFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        studentLabel = new javax.swing.JLabel();
        backButton = new javax.swing.JButton();
        yesStudentRadioButton = new javax.swing.JRadioButton();
        nameLabel = new javax.swing.JLabel();
        noStudentRadioButton = new javax.swing.JRadioButton();
        nameTextField = new javax.swing.JTextField();
        registerNumberLabel = new javax.swing.JLabel();
        lastNameLabel = new javax.swing.JLabel();
        registerNumberTextField = new javax.swing.JTextField();
        lastNameTextField = new javax.swing.JTextField();
        registerDateLabel = new javax.swing.JLabel();
        registerDateTextField = new javax.swing.JTextField();
        saveCustomerButton = new javax.swing.JButton();
        noteLabel = new javax.swing.JLabel();
        searchCustomerButton = new javax.swing.JButton();

        buttonGroup1.add(yesStudentRadioButton);
        buttonGroup1.add(noStudentRadioButton);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        studentLabel.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        studentLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        studentLabel.setText("Student");

        backButton.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        backButton.setText("Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        yesStudentRadioButton.setText("Yes");

        nameLabel.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        nameLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nameLabel.setText("Name");

        noStudentRadioButton.setText("No");
        noStudentRadioButton.setSelected(true);

        registerNumberLabel.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        registerNumberLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        registerNumberLabel.setText("Register number");

        lastNameLabel.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lastNameLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lastNameLabel.setText("Lastname");

        registerNumberTextField.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        registerNumberTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        registerDateLabel.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        registerDateLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        registerDateLabel.setText("Register date");

        registerDateTextField.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        registerDateTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        registerDateTextField.setEditable(false);

        saveCustomerButton.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        saveCustomerButton.setText("Save");
        saveCustomerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveCustomerButtonActionPerformed(evt);
            }
        });

        noteLabel.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        noteLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        noteLabel.setText("Enter customer register number");

        searchCustomerButton.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        searchCustomerButton.setText("Search");
        searchCustomerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchCustomerButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(registerDateLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(registerNumberLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(backButton))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(nameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lastNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(studentLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(15, 15, 15)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lastNameTextField, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(nameTextField)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(yesStudentRadioButton)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                                        .addComponent(noStudentRadioButton)
                                        .addGap(25, 25, 25))))
                            .addComponent(registerNumberTextField)
                            .addComponent(registerDateTextField)
                            .addComponent(noteLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(saveCustomerButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(searchCustomerButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(backButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(nameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lastNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(studentLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(yesStudentRadioButton)
                            .addComponent(noStudentRadioButton)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(nameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lastNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(2, 2, 2)
                .addComponent(registerDateLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(registerDateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(registerNumberLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(registerNumberTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(noteLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addComponent(searchCustomerButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(saveCustomerButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        this.dispose();

        UserEmployeeFrame f = new UserEmployeeFrame();
        f.setVisible(true);
        f.setLocationRelativeTo(null);
    }//GEN-LAST:event_backButtonActionPerformed

    private void saveCustomerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveCustomerButtonActionPerformed

       Session session = null;
       Transaction tx = null; 
       
       try
       {
       
            session = HibernateUtil.createSessionFactory().openSession();
            tx = session.beginTransaction();


            cus.setName(nameTextField.getText());
            cus.setLastName(lastNameTextField.getText());

            if(yesStudentRadioButton.isSelected())
            {
                cus.setIsStudent(true);
            }else
                cus.setIsStudent(false);
            //

            session.merge(cus);

            tx.commit();

            
            cus = null;
            registerNumberTextField.setEditable(true);

             JOptionPane.showMessageDialog(null, "Change saved");

       }catch(HibernateException e){
           if(session != null)
           {
               tx.rollback();
           }
       }finally{
           if(session != null)
           {
               HibernateUtil.closeHibernateUtil();  
           }
       }
    }//GEN-LAST:event_saveCustomerButtonActionPerformed

    private void searchCustomerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchCustomerButtonActionPerformed
        
        Session session = null;
        Transaction tx = null;
        

        try
        {
        session = HibernateUtil.createSessionFactory().openSession();
                
                Query q = session.createQuery("from Customer where register_number='" + registerNumberTextField.getText() + "'");
                
                tx = session.beginTransaction();
                List list = q.list();
                tx.commit();
                
                if(list.size() > 0)
                {
                    cus = (Customer)list.get(list.size()-1);
                    
                    nameTextField.setText(cus.getName());
                    lastNameTextField.setText(cus.getLastName());
                    registerDateTextField.setText(String.valueOf(cus.getRegisterDate()));
                    
                    if(cus.isIsStudent())
                    {
                        yesStudentRadioButton.setSelected(true);
                    }else
                        noStudentRadioButton.setSelected(true);
                    //
                    registerNumberTextField.setEditable(false);
                }
        }catch(HibernateException e){
            if(session != null)
            {
                tx.rollback();
            }
        }finally{
            if(session != null)
            {
                HibernateUtil.closeHibernateUtil();
            }
        }        
    }//GEN-LAST:event_searchCustomerButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditCustomerProfileFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditCustomerProfileFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditCustomerProfileFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditCustomerProfileFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditCustomerProfileFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel lastNameLabel;
    private javax.swing.JTextField lastNameTextField;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JTextField nameTextField;
    private javax.swing.JRadioButton noStudentRadioButton;
    private javax.swing.JLabel noteLabel;
    private javax.swing.JLabel registerDateLabel;
    private javax.swing.JTextField registerDateTextField;
    private javax.swing.JLabel registerNumberLabel;
    private javax.swing.JTextField registerNumberTextField;
    private javax.swing.JButton saveCustomerButton;
    private javax.swing.JButton searchCustomerButton;
    private javax.swing.JLabel studentLabel;
    private javax.swing.JRadioButton yesStudentRadioButton;
    // End of variables declaration//GEN-END:variables
}
